In [1]:
#PANDAS 
#NUMPY
#MATPLOTLIB
#SEABORN 

In [1]:
import pandas as pd
pd.set_option("display.max_columns",500)
pd.set_option("display.max_rows",500)

In [2]:
#conda install pandas

In [4]:
ls

Descriptive Analytics.ipynb             my_first_python_plot.jpg
IPL IMB381IPL2013.csv                   mycsv.csv
Pandas_Introduction.ipynb               myplot.jpg
Visualization_mat_seaborn_Latest.ipynb  myplot.png
auto-mpg.data                           numpy and plot.ipynb
example.jpg                             plot.jpg
example.png                             pythonplot.jpg
fi1.png                                 tem.csv
image.png                               train.csv
modified_df.csv                         weekend_afternoon_python.jpg
mtcars.csv


In [5]:
df=pd.read_csv("mtcars.csv")


In [6]:
type(df)

pandas.core.frame.DataFrame

In [7]:
df

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4


In [8]:
df.head(2)

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,21.0,6,160.0,110,3.9,2.620,16.46,0,1,4,4
1,21.0,6,160.0,110,3.9,2.875,17.02,0,1,4,4


In [9]:
df.shape

(32, 11)

In [10]:
df.tail(3)

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
29,19.7,6,145.0,175,3.62,2.77,15.5,0,1,5,6
30,15.0,8,301.0,335,3.54,3.57,14.6,0,1,5,8
31,21.4,4,121.0,109,4.11,2.78,18.6,1,1,4,2


In [13]:
df.sample(3)

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
5,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
14,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
16,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4


In [11]:
df.columns

Index(['mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am', 'gear',
       'carb'],
      dtype='object')

In [26]:
df.dtypes

mpg     float64
cyl       int64
disp    float64
hp        int64
drat    float64
wt      float64
qsec    float64
vs        int64
am        int64
gear      int64
carb      int64
dtype: object

In [38]:
df.describe()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
count,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.0000
mean,20.090625,6.187500,230.721875,146.687500,3.596563,3.217250,17.848750,0.437500,0.406250,3.687500,2.8125
std,6.026948,1.785922,123.938694,68.562868,0.534679,0.978457,1.786943,0.504016,0.498991,0.737804,1.6152
min,10.400000,4.000000,71.100000,52.000000,2.760000,1.513000,14.500000,0.000000,0.000000,3.000000,1.0000
25%,15.425000,4.000000,120.825000,96.500000,3.080000,2.581250,16.892500,0.000000,0.000000,3.000000,2.0000
50%,19.200000,6.000000,196.300000,123.000000,3.695000,3.325000,17.710000,0.000000,0.000000,4.000000,2.0000
75%,22.800000,8.000000,326.000000,180.000000,3.920000,3.610000,18.900000,1.000000,1.000000,4.000000,4.0000
max,33.900000,8.000000,472.000000,335.000000,4.930000,5.424000,22.900000,1.000000,1.000000,5.000000,8.0000


In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   mpg     32 non-null     float64
 1   cyl     32 non-null     int64  
 2   disp    32 non-null     float64
 3   hp      32 non-null     int64  
 4   drat    32 non-null     float64
 5   wt      32 non-null     float64
 6   qsec    32 non-null     float64
 7   vs      32 non-null     int64  
 8   am      32 non-null     int64  
 9   gear    32 non-null     int64  
 10  carb    32 non-null     int64  
dtypes: float64(5), int64(6)
memory usage: 2.9 KB


In [95]:
df.isna()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False


In [13]:
df.isna().sum()

mpg     0
cyl     0
disp    0
hp      0
drat    0
wt      0
qsec    0
vs      0
am      0
gear    0
carb    0
dtype: int64

In [45]:
df.min()

mpg     10.400
cyl      4.000
disp    71.100
hp      52.000
drat     2.760
wt       1.513
qsec    14.500
vs       0.000
am       0.000
gear     3.000
carb     1.000
dtype: float64

In [22]:
df.median()

mpg      19.200
cyl       6.000
disp    196.300
hp      123.000
drat      3.695
wt        3.325
qsec     17.710
vs        0.000
am        0.000
gear      4.000
carb      2.000
dtype: float64

In [14]:
df.var()

mpg        36.324103
cyl         3.189516
disp    15360.799829
hp       4700.866935
drat        0.285881
wt          0.957379
qsec        3.193166
vs          0.254032
am          0.248992
gear        0.544355
carb        2.608871
dtype: float64

In [22]:
df.std()

mpg       6.026948
cyl       1.785922
disp    123.938694
hp       68.562868
drat      0.534679
wt        0.978457
qsec      1.786943
vs        0.504016
am        0.498991
gear      0.737804
carb      1.615200
dtype: float64

In [7]:
df.quantile([0.50,0.25,0.75,0.82,1])

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0.50,19.200,6.0,196.300,123.0,3.695,3.32500,17.7100,0.0,0.0,4.0,2.0
0.25,15.425,4.0,120.825,96.5,3.080,2.58125,16.8925,0.0,0.0,3.0,2.0
0.75,22.800,8.0,326.000,180.0,3.920,3.61000,18.9000,1.0,1.0,4.0,4.0
0.82,25.072,8.0,354.780,209.2,4.080,3.80520,19.4526,1.0,1.0,4.0,4.0
1.00,33.900,8.0,472.000,335.0,4.930,5.42400,22.9000,1.0,1.0,5.0,8.0


In [75]:
df.vs.value_counts()

0    18
1    14
Name: vs, dtype: int64

In [49]:
df.gear.value_counts()

3    15
4    12
5     5
Name: gear, dtype: int64

# how to select specific columns in data

In [9]:
df[['mpg','hp']]

,mpg,hp
0,21.0,110
1,21.0,110
2,22.8,93
3,21.4,110
4,18.7,175
5,18.1,105
6,14.3,245
7,24.4,62
8,22.8,95
9,19.2,123


In [13]:

# selecting only one column
df["mpg"]
df.mpg
df[["mpg"]]

# selecting multiple columns

df[["mpg","hp"]]


,mpg,hp
0,21.0,110
1,21.0,110
2,22.8,93
3,21.4,110
4,18.7,175
5,18.1,105
6,14.3,245
7,24.4,62
8,22.8,95
9,19.2,123


In [108]:
df.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2


# loc/ iloc

In [20]:
df.head(4)

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1


In [18]:
df.loc[[0,1,2],["mpg","cyl","disp","hp"]]

,mpg,cyl,disp,hp
0,21.0,6,160.0,110
1,21.0,6,160.0,110
2,22.8,4,108.0,93


In [10]:
df.loc[1:3,"disp":"wt"]

,disp,hp,drat,wt
1,160.0,110,3.90,2.875
2,108.0,93,3.85,2.320
3,258.0,110,3.08,3.215


In [8]:
df.loc[2:3,"qsec":"carb"]

,qsec,vs,am,gear,carb
2,18.61,1,1,4,1
3,19.44,1,0,3,1


In [21]:
df.iloc[0:3,0:4]

,mpg,cyl,disp,hp
0,21.0,6,160.0,110
1,21.0,6,160.0,110
2,22.8,4,108.0,93


In [19]:
#df.loc
#df.iloc

df.loc[[0,1,2],["mpg","cyl","disp","hp"]]

df.iloc[0:3,0:4]


,mpg,cyl,disp,hp
0,21.0,6,160.0,110
1,21.0,6,160.0,110
2,22.8,4,108.0,93


In [21]:
df.loc[0:3,["mpg","cyl","disp","hp"]]

,mpg,cyl,disp,hp
0,21.0,6,160.0,110
1,21.0,6,160.0,110
2,22.8,4,108.0,93
3,21.4,6,258.0,110


In [118]:
df.iloc[0:3,0:5]

,mpg,cyl,disp,hp,drat
0,21.0,6,160.0,110,3.90
1,21.0,6,160.0,110,3.90
2,22.8,4,108.0,93,3.85


In [24]:
df.loc[22:24:2,:]

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
22,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
24,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2


In [26]:
df.iloc[21:28:4,:]

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
21,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
25,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1


In [61]:
# df.loc
# df.iloc

df.loc[[0,1,3],["mpg","cyl","hp"]]



,mpg,cyl,hp
0,21.0,6,110
1,21.0,6,110
3,21.4,6,110


In [27]:
df.iloc[3,5]

3.215

In [62]:
df.iloc[[0,1,2,4],0:4]

,mpg,cyl,disp,hp
0,21.0,6,160.0,110
1,21.0,6,160.0,110
2,22.8,4,108.0,93
4,18.7,8,360.0,175


In [50]:
df.loc[22:24,["mpg","cyl","qsec"]]

,mpg,cyl,qsec
22,15.2,8,17.30
23,13.3,8,15.41
24,19.2,8,17.05


In [74]:
df.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2


# filter 

In [33]:
df[df['hp']>200]

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
6,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
14,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
23,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
28,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
30,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8


In [116]:
df[df["gear"]==5]

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
26,26.0,4,120.3,91,4.43,2.140,16.7,0,1,5,2
27,30.4,4,95.1,113,3.77,1.513,16.9,1,1,5,2
28,15.8,8,351.0,264,4.22,3.170,14.5,0,1,5,4
29,19.7,6,145.0,175,3.62,2.770,15.5,0,1,5,6
30,15.0,8,301.0,335,3.54,3.570,14.6,0,1,5,8


In [12]:
df[(df["mpg"]>15)&(df["gear"]>4)]



,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
26,26.0,4,120.3,91,4.43,2.140,16.7,0,1,5,2
27,30.4,4,95.1,113,3.77,1.513,16.9,1,1,5,2
28,15.8,8,351.0,264,4.22,3.170,14.5,0,1,5,4
29,19.7,6,145.0,175,3.62,2.770,15.5,0,1,5,6


In [120]:
df[(df["gear"]==4)| (df["mpg"]>22) | (df["wt"]>2) ]

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4


In [14]:
df[(df["gear"]==4)|(df["gear"]==3)]

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4


# group by using pandas 

In [19]:
for idx,data in df.groupby(["gear","cyl"]):
    print("ID of the group ::: ",idx)


    print("data of the group ==> \n",data)
    print("=="*20)

ID of the group :::  (3, 4)
data of the group ==> 
      mpg  cyl   disp  hp  drat     wt   qsec  vs  am  gear  carb
20  21.5    4  120.1  97   3.7  2.465  20.01   1   0     3     1
ID of the group :::  (3, 6)
data of the group ==> 
     mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
3  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
5  18.1    6  225.0  105  2.76  3.460  20.22   1   0     3     1
ID of the group :::  (3, 8)
data of the group ==> 
      mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
4   18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2
6   14.3    8  360.0  245  3.21  3.570  15.84   0   0     3     4
11  16.4    8  275.8  180  3.07  4.070  17.40   0   0     3     3
12  17.3    8  275.8  180  3.07  3.730  17.60   0   0     3     3
13  15.2    8  275.8  180  3.07  3.780  18.00   0   0     3     3
14  10.4    8  472.0  205  2.93  5.250  17.98   0   0     3     4
15  10.4    8  460.0  215  3.00  5.424  17.82   0   0    

In [34]:
df.groupby(["gear"])["mpg"].mean()

gear
3    16.106667
4    24.533333
5    21.380000
Name: mpg, dtype: float64

In [22]:
df.groupby(["gear","cyl"])["mpg"].describe()

count    mean       std   min     25%    50%     75%   max
gear cyl                                                            
3    4      1.0  21.500       NaN  21.5  21.500  21.50  21.500  21.5
     6      2.0  19.750  2.333452  18.1  18.925  19.75  20.575  21.4
     8     12.0  15.050  2.774396  10.4  14.050  15.20  16.625  19.2
4    4      8.0  26.925  4.807360  21.4  22.800  25.85  30.900  33.9
     6      4.0  19.750  1.552417  17.8  18.850  20.10  21.000  21.0
5    4      2.0  28.200  3.111270  26.0  27.100  28.20  29.300  30.4
     6      1.0  19.700       NaN  19.7  19.700  19.70  19.700  19.7
     8      2.0  15.400  0.565685  15.0  15.200  15.40  15.600  15.8

In [52]:
df.groupby(["gear","cyl"])[["mpg"]].agg({"mean","count","std","var","max","median","quantile"})




mpg                                                   
           max count median quantile        var    mean       std
gear cyl                                                         
3    4    21.5     1  21.50    21.50        NaN  21.500       NaN
     6    21.4     2  19.75    19.75   5.445000  19.750  2.333452
     8    19.2    12  15.20    15.20   7.697273  15.050  2.774396
4    4    33.9     8  25.85    25.85  23.110714  26.925  4.807360
     6    21.0     4  20.10    20.10   2.410000  19.750  1.552417
5    4    30.4     2  28.20    28.20   9.680000  28.200  3.111270
     6    19.7     1  19.70    19.70        NaN  19.700       NaN
     8    15.8     2  15.40    15.40   0.320000  15.400  0.565685

In [127]:
df.groupby(["cyl","gear","vs"])[["mpg"]].mean()

mpg
cyl gear vs        
4   3    1   21.500
    4    1   26.925
    5    0   26.000
         1   30.400
6   3    1   19.750
    4    0   21.000
         1   18.500
    5    0   19.700
8   3    0   15.050
    5    0   15.400

In [131]:
#group by 
df.groupby(["gear","vs"])["mpg"].describe()

count       mean       std   min    25%    50%     75%   max
gear vs                                                              
3    0    12.0  15.050000  2.774396  10.4  14.05  15.20  16.625  19.2
     1     3.0  20.333333  1.934770  18.1  19.75  21.40  21.450  21.5
4    0     2.0  21.000000  0.000000  21.0  21.00  21.00  21.000  21.0
     1    10.0  25.240000  5.540999  17.8  21.75  23.60  29.625  33.9
5    0     4.0  19.125000  5.022201  15.0  15.60  17.75  21.275  26.0
     1     1.0  30.400000       NaN  30.4  30.40  30.40  30.400  30.4

In [34]:
pd.DataFrame([[1,2],[3,4]],columns=["a","b"],index=["a","b"])

,a,b
a,1,2
b,3,4


# how to add / delete a col

In [21]:
df["new_col"]=1

In [22]:
df.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,new_col
0,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,1
1,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,1
2,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,1
3,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,1
4,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,1


In [40]:
#add a new column
l=[]
for i in df["gear"]:
    if i%2==0:
        l.append("even")
    else:
        l.append("odd")
df["new_col"] =l   
df

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,new_col
0,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,even
1,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,even
2,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,even
3,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,odd
4,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,odd
5,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1,odd
6,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4,odd
7,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2,even
8,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2,even
9,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4,even


In [25]:
l=[]
for i in df["vs"]:
    if i==0:
        l.append("zero")
    else:
        l.append("non_zero")
df["new_col2"] =l   
df

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,new_col,new_col2
0,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,True,zero
1,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,True,zero
2,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,True,non_zero
3,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,True,non_zero
4,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,False,zero
5,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1,False,non_zero
6,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4,False,zero
7,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2,True,non_zero
8,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2,True,non_zero
9,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4,False,non_zero


In [23]:
df["new_col"]=df["mpg"]>=20

In [26]:
df

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,new_col,new_col2
0,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,True,zero
1,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,True,zero
2,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,True,non_zero
3,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,True,non_zero
4,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,False,zero
5,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1,False,non_zero
6,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4,False,zero
7,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2,True,non_zero
8,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2,True,non_zero
9,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4,False,non_zero


In [30]:
df.drop(["new_col","new_col2"],axis=1,inplace=True)


In [31]:
df

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4


In [53]:
df.drop([0],axis=0,inplace=True)

In [54]:
df.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
2,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4


# sorting the data

In [11]:
df=pd.read_csv("mtcars.csv")


In [26]:
df.sort_values(["hp"],ascending=[False])

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
30,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
28,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
6,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
23,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
16,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
15,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
14,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
13,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
11,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3


In [100]:
df.sort_values(["mpg","hp"],ascending=[False,True])

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
19,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
17,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
27,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
25,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
7,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
2,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
8,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
20,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1


# numpy intro

In [37]:
import numpy as np
#pip install numpy
#!pip install numpy
#conda install numpy

In [107]:
l=[[1,2],
   [2,3]]

In [56]:
type(l)

list

In [57]:
l+l

[[1, 1.0], [2, 3], [1, 1.0], [2, 3]]

In [108]:
a=np.array(l)
b=np.array([[4,5],
            [7,8]])

In [59]:
type(a)

numpy.ndarray

In [60]:
a

array([[1., 1.],
       [2., 3.]])

In [62]:
a.shape

(2, 2)

In [63]:
b

array([[4, 5],
       [7, 8]])

In [64]:
a+b

array([[ 5.,  6.],
       [ 9., 11.]])

In [65]:
a-b

array([[-3., -4.],
       [-5., -5.]])

In [66]:
a+1

array([[2., 2.],
       [3., 4.]])

In [67]:
a*2

array([[2., 2.],
       [4., 6.]])

In [68]:
a**2

array([[1., 1.],
       [4., 9.]])

In [51]:
a

array([[1, 2],
       [2, 3]])

In [52]:
b

array([[4, 5],
       [7, 8]])

In [53]:
b.T

array([[4, 7],
       [5, 8]])

In [54]:
a*b

array([[ 4, 10],
       [14, 24]])

In [ ]:
A-->(p,m) B ---> (m,n)

#number of col of A === number of rowa of B


In [21]:
np.dot(a,b)

array([[18, 21],
       [29, 34]])

In [20]:
np.matmul(a,b)

array([[18, 21],
       [29, 34]])

In [55]:
a

array([[1, 2],
       [2, 3]])

In [32]:
b=np.linalg.inv(a)

In [34]:
b

array([[-3.,  2.],
       [ 2., -1.]])

In [33]:
np.dot(a,b)

array([[1., 0.],
       [0., 1.]])

In [104]:
np.cos(3.14/2)

0.0007963267107332633

In [189]:
np.tan(22/7)

0.0012644899412945707

In [105]:
np.exp(1) #e^10

2.718281828459045

In [43]:
np.pi

3.141592653589793

In [18]:

#2^x=32

np.log2(32)

5.0

In [163]:
a

array([[1, 2],
       [2, 3]])

a[start:end:step,start:end:step]

In [167]:
a[::-1,:]

array([[2, 3],
       [1, 2]])

In [99]:
a

array([[1, 2],
       [2, 3]])

In [189]:
b

array([[4, 5],
       [7, 8]])

In [110]:
np.sum(b,axis=1)

array([ 9, 15])

In [99]:
a

array([[1, 2],
       [2, 3]])

In [49]:
np.median(a)

2.0

In [50]:

np.median(b,axis=1)

array([4.5, 7.5])

In [89]:
a

array([[1, 2],
       [2, 3]])

In [90]:
np.concatenate([a,a],axis=0)

array([[1, 2],
       [2, 3],
       [1, 2],
       [2, 3]])

In [91]:
np.concatenate([a,a],axis=1)

array([[1, 2, 1, 2],
       [2, 3, 2, 3]])

In [111]:
l=[[1,2,3],[3,4,5],[3,6,7]]
np.array(l)

array([[1, 2, 3],
       [3, 4, 5],
       [3, 6, 7]])

In [112]:
np.sum(l,axis=0)

array([ 7, 12, 15])

In [113]:
np.sum(l,axis=1)

array([ 6, 12, 16])

# inverse 


In [ ]:
ope---> +
identity=0 #5+0=5 10+0=10
a+b=0
b = -a


ope---->*
identity=1 # 5*1=5 10*1=10
a*b=1 
b=1/a


ope-->matmul

identity= np.array([[1,0],[0,1]])   # a*iden=a


inv= a*b =identity

In [114]:
a

array([[1, 2],
       [2, 3]])

In [115]:
b=np.array([[1,0],[0,1]])

In [151]:
np.matmul(a,b) 

array([[1, 2],
       [2, 3]])

In [153]:
ainv=np.linalg.inv(a)

In [154]:
a

array([[1, 2],
       [2, 3]])

In [155]:
ainv

array([[-3.,  2.],
       [ 2., -1.]])

In [156]:
np.matmul(a,ainv)

array([[1., 0.],
       [0., 1.]])

In [157]:
a

array([[1, 2],
       [2, 3]])

In [158]:
b

array([[1, 0],
       [0, 1]])

In [ ]:
1 2
2 3

In [159]:
b

array([[1, 0],
       [0, 1]])

In [161]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

# index 

In [ ]:
list,str,tuple,np.array,dataframe

In [69]:
a=[6,23,90,56,23,12,78,99,232]
#a[start:end:step]

In [88]:
a[::-1]

[232, 99, 78, 12, 23, 56, 90, 23, 6]

In [72]:
a[1:]

[23, 90, 56, 23, 12, 78, 99, 232]

In [73]:
a[:4]

[6, 23, 90, 56]

In [76]:
a[1:4:1]

[23, 90, 56]

In [77]:
a[1:4:2]

[23, 56]

In [27]:
a[1:4:3]

[23]

In [175]:
a[4:1:-1]

[78, 12, 23]

In [41]:
a="python"


In [42]:
a[1:4:1]

'yth'

In [182]:
a="hjh"
a==a[::-1]

True

In [183]:
fun =lambda a: a==a[::-1]

In [184]:
fun("mom")

True

In [185]:
fun("jhbfhed")

False

In [93]:
def fun(x):
    
    if x==x[::-1]:
        return True
    else:
        return False

In [95]:
fun("mom")

True

In [91]:
a="dad"

In [92]:
a[::-1]

'dad'